name: google_signin_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  transformer_page_view: ^0.1.6
  carousel_slider: ^4.0.0

  # google sign in
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  google_sign_in: ^5.0.7

  # state management
  provider: ^4.3.2+2

  # icon of google
  font_awesome_flutter: ^8.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/OnceUponAtimeTime.jpg
    - assets/theHustlejpg.jpg
    - assets/3Idiots.jpg
    - assets/AOT.jpg
    - assets/demonSlayer.jpg
    - assets/GoodBoys.jpg
    - assets/joker.jpg
    - assets/JustOneMoreEpisode.jpg
    - assets/addmovie.jpg